package io.chthonic.mechanicuslovecraft.common.valueobjects

import androidx.annotation.Keep

@Keep
sealed interface Role {
    val value: String

    companion object {
        fun validate(value: String): Role =
            when (value) {
                User.value -> User
                Assistant.value -> Assistant
                else -> Other(value)
            }
    }

    /**
     * Person interacting with the API
     */
    data object User : Role {
        override val value: String = "user"
    }

    /**
     * AI itself
     */
    data object Assistant : Role {
        override val value: String = "assistant"
    }

    /**
     * utomated or status messages generated by the system, not part of the conversational flow but rather meta-information about the system state or actions taken by the API
     */
    data object System : Role {
        override val value: String = "system"
    }

    @JvmInline
    value class Other(override val value: String) : Role
}
