package io.chthonic.mechanicuslovecraft.data.openai.rest.models

import androidx.annotation.Keep

@Keep
@JvmInline
internal value class Role(val value: String) {
    companion object {
        val USER = Role("user") // person interacting with the API
        val ASSISTANT = Role("assistant") // AI itself
        val SYSTEM = Role("system") // Automated or status messages generated by the system, not part of the conversational flow but rather meta-information about the system state or actions taken by the API
    }
}